name: Test & Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    env:
      node-version: '16.15.0'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cache NPM packages
        id: cache-npm
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.node_version}}
      - name: Set up node CI environment
        run: yarn --immutable
        if: steps.cache-npm.outputs.cache-hit != 'true'
      - name: Lint code
        run: yarn run lint

  test:
    name: Run all tests
    runs-on: ubuntu-latest
    env:
      node-version: '16.15.0'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cache NPM packages
        id: cache-npm
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.node_version}}
      - name: Set up node CI environment
        run: yarn --immutable
        if: steps.cache-npm.outputs.cache-hit != 'true'
      - name: Run Unit Test Suite
        run: yarn run test:unit
      - name: Run integration tests
        run: yarn run test:integration

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    env:
      node-version: '16.15.0'
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cache NPM packages
        id: cache-npm
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.node_version}}
      - name: Set up node CI environment
        run: yarn --immutable
        if: steps.cache-npm.outputs.cache-hit != 'true'
      - name: Release built code
        run: yarn run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
